### ISSUE TITLE
Error on executing Scheduler Task

### ISSUE THREAD

**Issue by SchmidtWebmedia** [schliesser/sitecrawler#5]
I get an error if I try to execute the Scheduler Task:
Oops, an error occurred!
Return value of "Schliesser\Sitecrawler\Command\CrawlSitemapCommand::execute()" must be of the type int, "null" returned.

Sitemap created with core TYPO3 Extension. Sitemap validator results its a valid Sitemap.

**Environment**: 
TYPO3 10.4.6 (Composer)
Sitecrwaler: 1.0.0
PHP: 7.4

**Settings**
Add Argument URL
No further argument headers

**Protocol**
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of "Schliesser\Sitecrawler\Command\CrawlSitemapCommand::execute()" must be of the type int, "null" returned. | TypeError thrown in file /vendor/symfony/console/Command/Command.php in line 261. Requested URL: https://www.example.de/typo3/index.php?route=%%2Fmodule%%2Fsystem%%2FtxschedulerM1&token=--AnonymizedToken--&tx_scheduler[execute][]=2	

Core: Error handler (BE): PHP Warning: Illegal string offset 'loc' in /public/typo3conf/ext/sitecrawler/Classes/Command/CrawlSitemapCommand.php line 138

**Comment by schliesser** [comment]
Thank you for the report. 

I think it's related to PR #1 and is caused by only a single entry in either the sitemap index or a sitemap. Should be fixed with in v1.0.1. Can you please verify?

**Comment by SchmidtWebmedia** [comment]
It looks good, thanks. 
One further question: Does it run recursive through the sitemap? Because the first entry links to an other sitemap for all pages. Or do I have to link the "pages sitemap" itself?

**Comment by schliesser** [comment]
You can do both. The command runs recursive trough all sitemaps which it finds. It first gathers all available urls which are no sitemaps and then processed the url list. Until now I've testet only two level sitemaps like TYPO3 or shopware build them. (See examples I use for the tests: https://gist.github.com/schliesser/042fe0d0780bde3f8223a74f25fbb3f1)
Some times it can make sense to crawl pages and news sitemaps separately. 

If you execute the command on the terminal you should see a progressBar and the count of urls which are found.

As the sitemaps are standardized, you can even crawl shopware sitemaps with it :-)

Happy crawling

**Comment by SchmidtWebmedia** [comment]
That's nice. Thank you. I will close this issue, everything works now.
